config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  scope :dashboard do
    get '/', to: 'dashboard#index', as: 'dashboard'
    resources :promotions
  end
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  # api
  namespace :api do
    resources :promotions, only: [:index]
  end
  
  root to: 'home#index'

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true

  before_create :set_promo_code
  
  def self.sizes
    {
      thumbnail: { resize: "300x300" },
    }
  end

  def sized(size)
    self.image.variant(Promotion.sizes[size]).processed
  end

  
  def self.search(search)
    if search
      self.find(self.search_basics(search))
    else
      self.all
    end
  
  end
  
  def self.search_basics(search)
    Promotion.where(
      "title ilike ? OR description ilike ?",
      "%#{search}%","%#{search}%"
    ).pluck(:id)
  end

  private

  def set_promo_code
    self.promocode = generate_promo_code
  end

  def generate_promo_code
    loop do
      promocode = "FRAVEO-#{SecureRandom.hex[0, 4].upcase}"
      break promocode unless Promotion.where(promocode: promocode).exists?
    end
  end



end

app/controllers/api/promotions_controller.rb
class Api::PromotionsController < ApplicationController
  def index
    promotions = Promotion.search(params[:search])
    render json: promotions, include: :image, status: 200
  end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'
  before_action :set_promotion, only: [:show, :edit, :update, :destroy]

  def index
    @promotions = current_user.promotions.all
  end

  def show
  end

  def new
    @promotion = current_user.promotions.build
  end

  def edit
  end

  def create
    @promotion = current_user.promotions.new(promotion_params)

    respond_to do |format|
      if @promotion.save
        format.html { redirect_to @promotion, notice: 'Promotion was successfully created.' }
        format.json { render :show, status: :created, location: @promotion }
      else
        format.html { render :new }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @promotion.update(promotion_params)
        format.html { redirect_to @promotion, notice: 'Promotion was successfully updated.' }
        format.json { render :show, status: :ok, location: @promotion }
      else
        format.html { render :edit }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @promotion.destroy
    respond_to do |format|
      format.html { redirect_to promotions_url, notice: 'Promotion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_promotion
      @promotion = Promotion.find(params[:id])
    end

    def promotion_params
      params.require(:promotion).permit(:title, :description, :image)
    end
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/promotions/_form.html.erb
<%= form_with(model: promotion, local: true) do |form| %>
<% if promotion.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

  <ul>
    <% promotion.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= form.label :image %>
  <%= form.file_field :image, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :title %>
  <%= form.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :description %>
  <%= form.text_area :description, class: 'form-control' %>
</div>

<div class="form-group">
  <% if promotion.persisted? %>
  <div class="float-right">
    <%= link_to 'Destroy', promotion, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
  </div>
  <% end %>

  <%= form.submit class: 'btn btn-primary' %>

  <% if promotion.persisted? %>
  <%= link_to "Cancel", promotion, class: "btn btn-link" %>
  <% else %>
  <%= link_to "Cancel", promotions_path, class: "btn btn-link" %>
  <% end %>
</div>
<% end %>

app/views/promotions/edit.html.erb
<h1>Edit Promotion</h1>

<%= render 'form', promotion: @promotion %>

app/views/promotions/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Promotions</h1>
  </div>

  <div class="col-sm-6 text-right">
    <%= link_to new_promotion_path, class: 'btn btn-primary' do %>
    Add New Promotion
    <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Promocode</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @promotions.each do |promotion| %>
      <%= content_tag :tr, id: dom_id(promotion), class: dom_class(promotion) do %>
      <td><%= promotion.title %></td>
      <td><%= promotion.description %></td>
      <td><%= promotion.promocode %></td>
      <td><%= link_to 'Show', promotion %></td>
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/promotions/new.html.erb
<h1>New promotion</h1>

<%= render 'form', promotion: @promotion %>

app/views/promotions/show.html.erb
<div class="page-header">
  <%= link_to promotions_path, class: 'btn btn-default' do %>
    All Promotions
  <% end %>
  <%= link_to edit_promotion_path(@promotion), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show promotion</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @promotion.title %></dd>

  <dt>Description:</dt>
  <dd><%= @promotion.description %></dd>

  <dt>Promocode:</dt>
  <dd><%= @promotion.promocode %></dd>
</dl>

<<%= image_tag  @promotion.image %>>